### PR TITLE
Rez update

### PR DESCRIPTION
**Pull request by DarkmatterVale**
Hi,

I have updated the repository to remove everything but Rez

### CODE REVIEW

**Comment by waddlesplash** [comment]
Huh?! This is OpenSumIt, no? Not OpenRez.

If you want a repo with just Rez you can make one yourself.

**Comment by DarkmatterVale** [comment]
I could just transfer ownership of my repository, that is also what PulkoMandy wanted me to do.

https://www.google-melange.com/gci/task/view/google/gci2014/5279481811959808

**Comment by pulkomandy** [comment]
You misunderstood me.
There should be two repos at the end:
- Thisone with Sum-It and without Rez
- The other one at HaikuArchives with only Rez and no Sum-It.

**Comment by DarkmatterVale** [comment]
Ok, sorry. Can I transfer my repository to one of you?

**Pull request closed without merging**
