### PR TITLE
Add new function implementation plan and related information

### PR DESCRIPTION
**Pull request by beos-zealot**

### CODE REVIEW

**Comment by waddlesplash** [comment]
What are the two files at the end?

**Comment by beos-zealot** [comment]
Spreadsheet files in sum-it format (list of not yet implemented functions and etc.)

**Comment by beos-zealot** [comment]
I think it would be better in the future to convert sum-it binary files (with usefull information which often changes) to .sylk\* format (OpenSum-It supports it). File in this format is plain text, so changes would be tracked simpler.

*Symbolic Link (SYLK) is a Microsoft file format typically used to exchange data between applications, specifically spreadsheets. SYLK files conventionally have a .slk suffix. Composed of only displayable ANSI characters, it can be easily created and processed by other applications, such as databases.

**Comment by waddlesplash** [comment]
Sounds like a good idea. In the future, please let me review changes before merging them, OK? I didn't look at this one too closely until after you merged it.

**Comment by beos-zealot** [comment]
Sorry, I have not resisted temptation to try new repo collab posibilities :) Ok, in the future i let review before merge.

P.S. short explanation - TODO file was deleted, because I created new issue for each todo item before pull request .

**Comment by waddlesplash** [comment]
@beos-zealot since you're doing somewhat steady work on OpenSumIt now, would you like me to move the repository to your account? (you would assume full ownership of the repo, and it would move to github.com/beos-zealot/OpenSumIt -- you'd have to delete your fork.)

**Comment by beos-zealot** [comment]
Ok, we can do that, since i am the only one who touched source code in the past couple years... hope that would change in future, but for now this move makes logic.

**Comment by waddlesplash** [comment]
@beos-zealot ok, you now have admin access to this repo only. The "admin" tab on the sidebar should appear, and there is a "transfer repository" button under "danger zone". Type "OpenSumIt" as the repo name, and "beos-zealot" as the transfer location.

**Comment by waddlesplash** [comment]
Let me know when you do it.

**Comment by beos-zealot** [comment]
Just did it! Thanks.

**Pull request merged**
